language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

travisdeployer:                  # our deployer config
    verbose: true               # verbose output the deployment?
    branches:                    # what branches do you want to deploy?
        develop: develop         # deploys stage develop when merging into develop
        master: production       # deploys stage production when merging into master

after_success:                   # after your build succeeded (tests passed)
  - vendor/bin/travisdeployer  # Trigger the travis deployer